version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular-ecosystem:
        patterns:
          - "@angular/*"
          - "typescript"
          - "zone.js"
          - "tslib"
    ignore:
      - dependency-name: "@angular/*"
        versions: [">= 20.0.0"]
    versioning-strategy: "increase-if-necessary"

