version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@angular/core"
        versions: ["*"]
      - dependency-name: "@angular/cli"
        versions: ["*"]
      - dependency-name: "@angular/compiler"
        versions: ["*"]
      - dependency-name: "@angular/common"
        versions: ["*"]
      - dependency-name: "@angular/forms"
        versions: ["*"]
      - dependency-name: "@angular/router"
        versions: ["*"]
      - dependency-name: "@angular/platform-browser"
        versions: ["*"]
      - dependency-name: "@angular/platform-browser-dynamic"
        versions: ["*"]

    versioning-strategy: "increase"

