version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "angular"
        versions: ["*"]
    versioning-strategy: "increase"

