[build]
  command = "ng build --configuration production"
  publish = "dist/astronews.ui"
[build.environment]
api_key = "0fu6kxm8VJ28tAbk0iRAfazBSiqBW5v344fYDIiR"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
