[build]
  command = "ng build --configuration production"
  publish = "dist/astronews.ui"
[build.environment]
  api_key = ""
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
